### ISSUE TITLE
`typeid_generate` Casting Error

### ISSUE THREAD

**Issue by shellscape** [jetpack-io/typeid-sql#2]
Hey there. I just added the three functions (`typeid_generate`, `typeid_check`, `uuid_generate_v7`) to the database and ran 

```sql
select typeid_generate('test');
```

But was greeted with this error output:

```
Query 1 ERROR: ERROR:  returned record type does not match expected record type
DETAIL:  Returned type uuid does not match expected type text in column 1.
CONTEXT:  PL/pgSQL function typeid_generate(text) while casting return value to function's return type
```

Running `select uuid_generate_v7();` works fine for what it's worth.

Not sure if there's a postgres version mismatch but we're on `PostgreSQL 15.1 on aarch64-unknown-linux-gnu, compiled by gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0, 64-bit`

**Comment by shellscape** [comment]
This ended up being an error here: https://github.com/jetpack-io/typeid-sql/blob/6fb55550b59e716215f73c381cd5926e1b501a81/sql/typeid.sql#L9

`typeid_generate` is returning `(uuid, text)` and your type definition is expecting `(text, uuid)`

Probably good to correct that

**Comment by loreto** [comment]
I just opened this PR https://github.com/jetpack-io/opensource/pull/81 to address it
